// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa9y-dwZCWLwuGa6O1cMAAPiQ58F7Xi9Y',
    appId: '1:732124749864:web:f45bd820d59155fef3d51d',
    messagingSenderId: '732124749864',
    projectId: 'smart-home-73873',
    authDomain: 'smart-home-73873.firebaseapp.com',
    storageBucket: 'smart-home-73873.firebasestorage.app',
    measurementId: 'G-MKNTZLKTML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcPjxYUDd02smog5CynGlQJR-ZbkDBK3w',
    appId: '1:732124749864:android:401462a2dac71c08f3d51d',
    messagingSenderId: '732124749864',
    projectId: 'smart-home-73873',
    storageBucket: 'smart-home-73873.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBIOYwYmyWd54Hkho9FxBtDRcPnAjsHPQ',
    appId: '1:732124749864:ios:0c066fba1e6989d9f3d51d',
    messagingSenderId: '732124749864',
    projectId: 'smart-home-73873',
    storageBucket: 'smart-home-73873.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa9y-dwZCWLwuGa6O1cMAAPiQ58F7Xi9Y',
    appId: '1:732124749864:web:6ab56af0e4bc5918f3d51d',
    messagingSenderId: '732124749864',
    projectId: 'smart-home-73873',
    authDomain: 'smart-home-73873.firebaseapp.com',
    storageBucket: 'smart-home-73873.firebasestorage.app',
    measurementId: 'G-PV8HLBQTS1',
  );
}
